2023/07/17 월요일
HTTP 상태 500 – 내부 서버 오류
근본 원인 (root cause)
org.mybatis.spring.MyBatisSystemException: nested exception is
org.apache.ibatis.builder.IncompleteElementException: Could not find
parameter map java.util.Map
<insert id="insertNewArticle"
 <insert id="insertNewArticle" parameterMap="java.util.Map">
 ->
<insert id="insertNewArticle" parameterType="map">


500에러 중 하나
매퍼 파일의 아이디와 다오의 아이디가 일치하지 않으면 오류가 남